name: WindowsCMake

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_TRIPLET: x64-windows

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: List Environment
      run: Write-Host $env:PATH

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
  
    - name: Install dependencies
      run: |
        vcpkg install fftw3 boost-test boost-program-options boost-random hdf5 hdf5[cpp]
        vcpkg list
        dir c:\
        dir d:\
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      shell: PowerShell
      run: cmake $env:GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$env:BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: PowerShell
      run: cmake --build . --config $env:BUILD_TYPE



